{% set name = "cinema4d" %}
{% set display_name = "Cinema4D" %}
{% set version_major = "2025" %}
{% set version_minor = "1" %}
{% set version_patch = "2" %}
{% set version = version_major + "." + version_minor + "." + version_patch %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: archive_files/{{ display_name }}_{{ version_major }}_{{ version }}_Win.zip # [win64]
  sha256: 7fa63576db7eca3b4c8b62f192e8e9e612dd9c59ad365fcc5faba20c0fd06069
  folder: cinema4d

build:
  number: 0
  binary_relocation: False
  detect_binary_files_with_prefix: False
  # The binary is built to be relocatable, so can ignore the warnings about DSOs.
  missing_dso_whitelist:
  - "**"

test:
 commands:
   # Turning off the test because Cinema4D tries to pull a license even when
   # just printing the help text
   # - Commandline -help

about:
  home: https://www.maxon.net/en/cinema-4d
  license: Commercial
  summary: >
    3D computer animation, modeling, simulation, and rendering software